TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map
  robot_base_frame: base_link

  # kinematik model (Ackermann)
  teb_autosize: false
  max_global_plan_lookahead_dist: 3.0
  max_vel_lin: 1.0
  max_vel_ang: 0.5
  acc_lim_x: 0.5
  acc_lim_theta: 1.0

  # minimum dönüş yarıçapı
  min_turning_radius: 0.4  # metre cinsinden, gerçek aracınızın değeri

  # footprint
  footprint_model:
    type: polygon
    vertices: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]]
